server:
  port: 8290
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/threads
    username: postgres
    password: root123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: t_subscription
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update

